.PHONY : sample_1
sample_1 :
	ocamlbuild -pkg sqlite3 sample_1.native
.PHONY : sample_2
sample_2 :
	ocamlbuild -pkg sqlite3 sample_2.native
.PHONY : sample_3
sample_3 :
	ocamlbuild -pkg sqlite3 sample_3.native
.PHONY : clean
clean :
	rm -rf _build && rm *.native
